server:
  port: 8282

spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://localhost:54320/commande-bd?currentSchema=commande-api&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    #url: jdbc:postgresql://localhost:5432/postgres?currentSchema=commande&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: Mouhamed1
    #username: postgres
    #password: Mouhamed1
    driver-class-name: org.postgresql.Driver
  #sql:
  #  init:
  #    platform: postgres
  #    schema-locations: classpath:init-schema.sql,classpath:init-data.sql
  #    mode: always

  application:
    name: commande-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8989/auth/realms/order-app-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
jwt:
  auth:
    converter:
      resource-id: order-app
      principal-attribute: preferred_username